version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80" # Map host port 8000 to container port 80
    volumes:
      - .:/var/www/html # Mount the current directory to the container's web root
    depends_on:
      - db
    environment:
      # Laravel environment variables, ensure DB_HOST matches the service name 'db'
      DB_CONNECTION: mysql
      DB_HOST: 35.239.113.2
      #35.193.211.154
      DB_PORT: 3306
      DB_DATABASE: admin_exam
      DB_USERNAME: root
      DB_PASSWORD: Examadmin@2025
      APP_KEY: base64:TB5cXc7Y1rlQGQAXnHJEnZoJdc68pt6QLSTiqWX16Fs= # Generate with 'php artisan key:generate'
      # Other Laravel environment variables as needed

  db:
    image: mysql:8.0 # Use a specific MySQL version
    ports:
      - "3306:3306" # Map host port 3306 to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: Examadmin@2025
      MYSQL_DATABASE: admin_exam
      MYSQL_USER: ExamAdmin_user
      MYSQL_PASSWORD: ExamAdmin@123
    volumes:
      - db_data:/var/lib/mysql # Persist database data

volumes:
  db_data: # Define a named volume for database persistence
